### ISSUE TITLE
Do you still have a zip for all the empty models folders

### ISSUE THREAD

**Issue by jbzdarkid** [gabrielwoj/hlmv-resources#1]
The [HLMV setup page](https://wiki.teamfortress.com/wiki/Help:Model_Viewer#Models) links to this repo, and it's saying that you (used to) have a zip with all of the empty models/ folders, so that HLMV wouldn't give empty path warnings.
Do you still have this / could you remake it?

**Comment by gabrielwoj** [comment]
Yeah. It's here: [https://github.com/gabrielwoj/hlmv-resources/raw/main/VPKs%20-%20ZIPs%20-Releases/HLMV%20-%20Missing%20Folders%20Fix.zip](https://github.com/gabrielwoj/hlmv-resources/raw/main/VPKs%20-%20ZIPs%20-Releases/HLMV%20-%20Missing%20Folders%20Fix.zip)

Recently, I updated the Help:HLMV page to fix some broken links, and apparently I forgot that one, I'm sorry. The .zip pack is somewhat outdated though, I'll see if I can update anytime soon.

Thank you for your input.
